### ISSUE TITLE
Network Error cordova android@8.0.0[bug]

### ISSUE THREAD

**Issue by ShirazCoders** [apache/cordova-plugin-whitelist#43] opened 2019-06-13 16:22 UTC
Hello,
This is my repo: https://github.com/alighasemzadeh/srssms-mobile
I use cordova-android@8.0.0 with whitelist@1.3.3 but allways I get network error on mobile device and emulator.
When I downgrade cordova-android@6.4.0 It fixed.
I think there is bug with this plugin.

**Comment by alighasemzadeh** [comment] 2019-06-16 01:47
@janpio 
Did you find my problem and any solution?

**Comment by janpio** [comment] 2019-06-16 10:31
Deleting the bug issue template of a project is a sure way to move your issue to the bottom of the pile. Mentioning contributors and committers in your comments that did not talk to you before and reply to your issue is also impolite.

**Comment by bathindavarinder** [comment] 2019-06-18 18:06
any update on this? I am also facing similar issue.

**Comment by janpio** [comment] 2019-06-18 18:35
Then please create an issue where you do not delete the issue template, but describe the actual problem - maybe we can look at it and help.

**Comment by alighasemzadeh** [comment] 2019-06-19 14:18
Hello,
Our problem is clear. 
cordova-plugin-whitelist not work with cordova@8.0.0.
It work with 7.X.X and 6.X.X but not work with 8.X.X.

**Comment by janpio** [comment] 2019-06-19 15:01
No it is not to me, otherwise I wouldn't ask you for more information.

Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by alighasemzadeh** [comment] 2019-06-19 15:19
I create repository of my code: https://github.com/alighasemzadeh/srssms-mobile (Check my first post, It is clean version of cordova with cordova-android and cordova-whitelist).

I think problem is about cordova-android not cordova-plugin-whitelist.
cordova-plugin-whitelist works with any version of cordova-android expect 8.x.x

**Comment by alighasemzadeh** [comment] 2019-07-08 14:54
@janpio
I update whitelist plugin to 1.3.4
But it doesn't work.

**Comment by tux240** [comment] 2019-07-08 19:31
Hello,
I have the same. An OPTIONS error on each api request on emulator and device.
I'm using cordova 9 and cordova-android 8.

**Comment by willianslash** [comment] 2019-08-07 13:52
Hi! I have good news!

After searching all day on internet I found a solution for this problem.

All you have to do is include on AndroidManifest.xml the following key-pair-value on the application tag:

android:usesCleartextTraffic="true"

On API 28 this attribute is set false for default(for security reasons), in previous Android API is was true.

As follow in Google documentation:

android:usesCleartextTraffic
Indicates whether the app intends to use cleartext network traffic, such as cleartext HTTP. The default value for apps that target API level 27 or lower is "true". Apps that target API level 28 or higher default to "false".
When the attribute is set to "false", platform components (for example, HTTP and FTP stacks, DownloadManager, and MediaPlayer) will refuse the app's requests to use cleartext traffic. Third-party libraries are strongly encouraged to honor this setting as well. The key reason for avoiding cleartext traffic is the lack of confidentiality, authenticity, and protections against tampering; a network attacker can eavesdrop on transmitted data and also modify it without being detected.


So, I think the apache cordova could anticipating this information for developers... And the most important is to update the whitelist plugin with this information.

**Comment by alighasemzadeh** [comment] 2019-08-09 13:04
@willianslash 
Hello,
I did this job but it doesn't work.
Can you explain more?

**Comment by willianslash** [comment] 2019-08-09 13:20
Man, paste your AndroidManifest.xml here.

**Comment by alighasemzadeh** [comment] 2019-08-09 13:32
````
<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="10001" android:versionName="1.0.1" package="ir.srssms.app" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:usesCleartextTraffic="true" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
    <uses-sdk android:minSdkVersion="19" android:targetSdkVersion="28" />
</manifest>
```
@willianslash

**Comment by willianslash** [comment] 2019-08-09 14:27
I have found your issue:

The android:usesCleartextTraffic="true" attribute must be on the **_application_** tag, not in the **activity**, so your manifest should look like this:

<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="10001" android:versionName="1.0.1" package="ir.srssms.app" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true" android:usesCleartextTraffic="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
    <uses-sdk android:minSdkVersion="19" android:targetSdkVersion="28" />
</manifest>

**Comment by EdisonWerle** [comment] 2019-08-15 20:05
Hello! I have the same problem on emulators with android 9. I have already tested the solution suggested by @willianslash and it did not work, using emulator or cell with android 8 works.

**Comment by willianslash** [comment] 2019-08-16 20:42
> Hello! I have the same problem on emulators with android 9. I have already tested the solution suggested by @willianslash and it did not work, using emulator or cell with android 8 works.

Edison, please, copy your Android Manifest xml here...

**Comment by EdisonWerle** [comment] 2019-08-19 11:44
Hello @willianslash!

I solved it. 
I put your configuration in config.xml and it goes automatically to AndroidManifest.xml as you said


` <platform name="android">
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge"  target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
            <application android:networkSecurityConfig="@xml/network_security_config" />
            <application android:usesCleartextTraffic="true" />
        </edit-config>
        <resource-file src="resources/android/xml/network_security_config.xml" target="app/src/main/res/xml/network_security_config.xml" />
        <allow-intent href="market:*" />
.
.
.
`

I also changed in resources / android / xml / network-security-config.xml authorizing the domains.


`<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">localhost</domain>
        <domain includeSubdomains="true">192.232.233.145</domain>
        <domain includeSubdomains="true">192.168.1.12</domain>
    </domain-config>
</network-security-config>`

Thanks @willianslash

**Comment by willianslash** [comment] 2019-08-19 19:15
> Hello @willianslash!
> 
> I solved it.
> I put your configuration `android:usesCleartextTraffic="true"` in config.xml and it goes automatically to AndroidManifest.xml as you said
> 
> ```
>  <platform name="android">
>         <edit-config file="app/src/main/AndroidManifest.xml" mode="merge"  target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
>             <application android:networkSecurityConfig="@xml/network_security_config" />
>             <application android:usesCleartextTraffic="true" />
>         </edit-config>
>         <resource-file src="resources/android/xml/network_security_config.xml" target="app/src/main/res/xml/network_security_config.xml" />
>         <allow-intent href="market:*" />
> .
> .
> .
> ```
> 
> I also changed in resources / android / xml / network-security-config.xml authorizing the domains.
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <network-security-config>
>     <domain-config cleartextTrafficPermitted="true">
>         <domain includeSubdomains="true">localhost</domain>
>         <domain includeSubdomains="true">192.232.233.145</domain>
>         <domain includeSubdomains="true">192.168.1.12</domain>
>     </domain-config>
> </network-security-config>
> ```
> 
> Thanks @willianslash

You are welcome Edison!

**Comment by murphp15** [comment] 2019-09-13 20:07
@willianslash  This worked perfect! thanks your a star !

**Comment by willianslash** [comment] 2019-09-16 16:57
> @willianslash This worked perfect! thanks your a star !

I'm very glad Murph!

**Comment by kovacs-tamas** [comment] 2019-10-08 13:44
I have the also issues. I always get the following error message when i want to connect to a server:

```
XMLHttpRequest cannot load https://staging-server.****.com/version. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
``` 
I've never saw OPTIONS request before, no errors or warning in Monitor.


```bash
Ionic:

   ionic (Ionic CLI) : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework   : ionic1 1.3.3
   @ionic/v1-toolkit : 2.0.11

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.1.0
   Cordova Plugins       : no whitelisted plugins (29 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/tamas/Library/Android/sdk/)
   ios-deploy        : 1.9.2
   ios-sim           : 8.0.2
   NodeJS            : v10.15.3 (/usr/local/lib/node_modules/node/bin/node)
   npm               : 2.15.12
   OS                : macOS
   Xcode             : Xcode 11.0 Build version 11A420a
```

My network_security_config:

```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">127.0.0.1</domain>
        <domain includeSubdomains="true">******.com</domain>
        <domain includeSubdomains="true">">******.com</domain>
        <domain includeSubdomains="true">staging-server-******.com</domain>
        <domain includeSubdomains="true">server.****.com</domain>
    </domain-config>
</network-security-config>
```

Config.xml parts:

```xml

    <access origin="*" />
    <allow-intent href="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <allow-navigation href="*" />

<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
    <application android:networkSecurityConfig="@xml/network_security_config" />
    <application android:usesCleartextTraffic="true" />
</edit-config>
<resource-file src="resources/android/xml/network_security_config.xml" target="app/src/main/res/xml/network_security_config.xml" />
```

The generated Manifest.xml contains the needed parts:

```xml
<application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:networkSecurityConfig="@xml/network_security_config" android:supportsRtl="true" android:usesCleartextTraffic="true">
```
I've tried with Crosswalk and IonicWebview also, i use the latest version: **1.3.4** 
The strange thing, i've tried a workaround, when i always return true in the WhitelistPlugin.java, but the problem still exists

```java
    @Override
    public Boolean shouldAllowRequest(String url) {

        return true;

        // if (Boolean.TRUE == shouldAllowNavigation(url)) {
        //     return true;
        // }
        // if (allowedRequests.isUrlWhiteListed(url)) {
        //     return true;
        // }
        // return null; // Default policy
    }
```

**Comment by breautek** [comment] 2019-10-08 13:52
> XMLHttpRequest cannot load https://staging-server.****.com/version. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

This is a CORS error. It happens on devices that uses a CORS enabled webview, which is most modern devices. It's a backend configuration. Your server should respond to `OPTIONS` method on every API and it should return exactly 0 bytes in content in the `OPTIONS` request. It should also supply the CORS headers. CORS is a big topic that is unrealistically for me to explain how to use here, but you can read more about it on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)

**Comment by fonini** [comment] 2019-11-26 21:02
Thank you, @willianslash!
Been banging my head for two days after an SDK update.

**Comment by mAb1she** [comment] 2019-12-25 07:46
Thank you @willianslash 
It works!

**Comment by orhan-swe** [comment] 2020-02-03 15:30
@EdisonWerle 

Thanks!

One thing:
> I also changed in resources / android / xml / **network-security-config.xml** authorizing the domains.

is wrong, it should be: **network_security_config.xml** as that is how you reference the file from config.xml

Also for anyone else with this problem, network_security_config.xml is only needed if you want to enforce https on all traffic except for what you specify in: network_security_config.xml If you do not care about that as your prod server always uses https then network_security_config.xml is not needed and you can just update config.xml with:

```
<edit-config file="app/src/main/AndroidManifest.xml" mode="merge"  target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
            <application android:usesCleartextTraffic="true" />
        </edit-config>
```

**Comment by dddpoka** [comment] 2020-06-03 18:08
I have the same error. The solution helped for android 9. But android 10 (real device) also does not want to work.
I think that something else needs to be added for android 10

**Comment by philpx32** [comment] 2020-08-30 11:46
> Hi! I have good news!
> 
> After searching all day on internet I found a solution for this problem.
> 
> All you have to do is include on AndroidManifest.xml the following key-pair-value on the application tag:
> 
> android:usesCleartextTraffic="true"
> 
> On API 28 this attribute is set false for default(for security reasons), in previous Android API is was true.
> 
> As follow in Google documentation:
> 
> android:usesCleartextTraffic
> Indicates whether the app intends to use cleartext network traffic, such as cleartext HTTP. The default value for apps that target API level 27 or lower is "true". Apps that target API level 28 or higher default to "false".
> When the attribute is set to "false", platform components (for example, HTTP and FTP stacks, DownloadManager, and MediaPlayer) will refuse the app's requests to use cleartext traffic. Third-party libraries are strongly encouraged to honor this setting as well. The key reason for avoiding cleartext traffic is the lack of confidentiality, authenticity, and protections against tampering; a network attacker can eavesdrop on transmitted data and also modify it without being detected.
> 
> So, I think the apache cordova could anticipating this information for developers... And the most important is to update the whitelist plugin with this information.

@willianslash Damn, it worked like a charm. Thanks abunch

**Comment by dolphinpos** [comment] 2020-12-16 10:41
Hi All

I also have the same problem, can someone help me

below is my AndroidMainfest.xml code

<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="1" android:versionName="0.0.1" package="io.ionic.starter" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:networkSecurityConfig="@xml/network_security_config" android:supportsRtl="true" android:usesCleartextTraffic="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <service android:name="de.appplant.cordova.plugin.background.ForegroundService" />
        <provider android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true" android:name="org.apache.cordova.camera.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/camera_provider_paths" />
        </provider>
    </application>
    <uses-sdk android:minSdkVersion="19" android:targetSdkVersion="28" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.USB" android:required="false" />
    <uses-feature android:name="android.hardware.usb" android:required="false" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
</manifest>

**Comment by dddpoka** [comment] 2020-12-16 14:33
Following solution worked for me-

goto resources/android/xml/network_security_config.xml Change it to-

<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">localhost</domain>
        <domain includeSubdomains="true">api.example.com(to be adjusted)</domain>
    </domain-config>
</network-security-config>

**Comment by breautek** [comment] 2020-12-16 14:49
I'm closing this issue because the OP's issue is not clear and the direction of this thread has diverged into multiple areas.

There are two different issues that eventually have been discussed throughout this thread.

If you're communicating with non-secure sites (ie servers served over `http` instead of `https`), Android now blocks them by default. The server should be updated to serve through https instead. But if for some reason you cannot make this change, this [comment](https://github.com/apache/cordova-plugin-whitelist/issues/43#issuecomment-519107090) may be a workaround for you.

If you're seeing an error similar to this one below:
```
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
```

Then you must update your server to enable [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). This [comment](https://github.com/apache/cordova-plugin-whitelist/issues/43#issuecomment-539524095) may help you. I also have a [blog post](https://breautek.com/2020/07/14/enabling-cors/) that goes into more depth on how to enable CORS.

**Closed by breautek** 2020-12-16 14:49 UTC
Labels: support
