### ISSUE TITLE
Network Request Whitelist access origin="*" still block any ajax request

### ISSUE THREAD

**Issue by cyclonmaster** [apache/cordova-plugin-whitelist#60] opened 2021-05-07 01:06 UTC
# Bug Report
Network Request Whitelist to aloow any requests did not work

## Problem
error:
Access to XMLHttpRequest at 'https://xxx' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### What is expected to happen?

It suppose to allowed ajax request to https://xxx

### What does actually happen?

ajax request to https://xxx was blocked by cors policy

### Environment, Platform, Device

Device: Redmi Note 9S, Android 10

### Version information

Cordova Android platform version 9.1.0
cordova-plugin-whitelist Version 1.3.4
Webview Version 90.0.4430.91

config.xml
<access origin="*" />

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by breautek** [comment] 2021-05-07 01:22
CORS is a webview feature that isn't overridable. The whitelist plugin does not control this access feature.

The server needs to be configured to send the appropriate headers for CORS enabled webview/browsers.

You can find more information on this at:

https://breautek.com/articles/enabling-cors.html (article is focused around iOS WkWebView but the same applies for android webviews as well)

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

If you need further assistance, I'll invite you to our [Slack](http://slack.cordova.io/) community.

Closing this as not a bug / wont fix.

**Closed by breautek** 2021-05-07 01:22 UTC

**Comment by cyclonmaster** [comment] 2021-05-07 01:38
> CORS is a webview feature that isn't overridable. The whitelist plugin does not control this access feature.
> 
> The server needs to be configured to send the appropriate headers for CORS enabled webview/browsers.
> 
> You can find more information on this at:
> 
> https://breautek.com/articles/enabling-cors.html (article is focused around iOS WkWebView but the same applies for android webviews as well)
> 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
> 
> If you need further assistance, I'll invite you to our [Slack](http://slack.cordova.io/) community.
> 
> Closing this as not a bug / wont fix.

yes, please. invite me to slack.
I use firebase, and sometime a simple json file I store in github which not actually a server based. I cannot configured cors setting at the server. previously it work, only now it don't.

**Comment by breautek** [comment] 2021-05-07 03:13
Use the slack link for invite (its open to anyone)

http://slack.cordova.io/

I'm not familiar with Firebase but you may require a proxy server.

**Comment by freescout-helpdesk** [comment] 2021-08-22 19:25
On Android with the following in `config.xml` we are able to perform ajax requests to any servers and URLs:
```
<access origin="*" />
<plugin name="cordova-plugin-whitelist" spec="1.3.4" />
<engine name="android" spec="^8.1.0" />
```

But now we are building **exactly** the same app for iOS, but ajax requests do not work (checked on iPhone, iOS 12.4.0):
```
<access origin="*" />
<plugin name="cordova-plugin-whitelist" spec="1.3.4" />
<engine name="cordova-ios" spec="5.1.1" />
```

**Comment by freescout-helpdesk** [comment] 2021-08-23 06:38
It does looks like cordova-android does not need "Access-Control-Allow-Origin *" header on the server, while cordova-ios needs.

**Comment by freescout-helpdesk** [comment] 2021-08-23 08:56
> It does looks like cordova-android does not need "Access-Control-Allow-Origin *" header on the server, while cordova-ios needs.

Cordova community on Slack confirmed this.

It would be good to have this mentioned on https://github.com/apache/cordova-plugin-whitelist homepage for example. As it is not mentioned on any Cordova resources and developers will continue to spend hours and days trying to figure out why their Cordova apps are able to send ajax requests to any external addresses on Android, but unable on iOS.

**Comment by erisu** [comment] 2021-08-23 12:15
This plugin has been deprecated, will be archived shortly, and most likely will not be accepting any changes (PRs) to this repo.

I recommend that you open an issue ticket to fix the **Allow List** documentation in the `cordova-docs` repo.

We also welcome contributions/PRs if you like the help out and have time to spare. Again make sure it is on the `cordova-docs` repos.

The changes should be in this file: https://github.com/apache/cordova-docs/blob/master/www/docs/en/dev/guide/appdev/allowlist/index.md
